### ISSUE TITLE
Collectfast==0.6.0 + boto3==1.5.8 + Heroku = :(

### ISSUE THREAD

**Issue by webyneter** [antonagestam/collectfast#121]
**What**:
`Collectfast==0.6.0` and `boto3==1.5.8` don't play well when deploying to Heroku, resulting in

```shell
Traceback (most recent call last):
remote:          File "manage.py", line 30, in <module>
remote:            execute_from_command_line(sys.argv)
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
remote:            utility.execute()
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
remote:            self.fetch_command(subcommand).run_from_argv(self.argv)
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 206, in fetch_command
remote:            klass = load_command_class(app_name, subcommand)
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 40, in load_command_class
remote:            module = import_module('%s.management.commands.%s' % (app_name, name))
remote:          File "/app/.heroku/python/lib/python3.6/importlib/__init__.py", line 126, in import_module
remote:            return _bootstrap._gcd_import(name[level:], package, level)
remote:          File "<frozen importlib._bootstrap>", line 994, in _gcd_import
remote:          File "<frozen importlib._bootstrap>", line 971, in _find_and_load
remote:          File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
remote:          File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
remote:          File "<frozen importlib._bootstrap_external>", line 678, in exec_module
remote:          File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/collectfast/management/commands/collectstatic.py", line 8, in <module>
remote:            from collectfast.etag import should_copy_file
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/collectfast/etag.py", line 10, in <module>
remote:            from storages.utils import safe_join
remote:        ImportError: cannot import name 'safe_join'
remote: 
remote:  !     Error while running '$ python manage.py collectstatic --noinput'.
remote:        See traceback above for details.
``` 

**I'm also using**:
```env
django-storages==1.5.0  # pyup: ==1.5.0
```

**Solution**:
Downgrade
```env
Collectfast==0.5.2 # pyup: ==0.5.2
```

**Comment by antonagestam** [comment]
That looks like it's related to django-storages and not to boto3. Does upgrading django-storages help?

**Comment by webyneter** [comment]
@antonagestam sorry for the late response, I will try upgrading django-storages to 1.6; thank you for the tip :)

**Comment by antonagestam** [comment]
@webyneter No worries. Thanks for reporting the bug!
