### ISSUE TITLE
manage.py   collectstatic  report "no attribute 'preload_metadata"

### ISSUE THREAD

**Issue by luojiyin1987** [antonagestam/collectfast#126]
Django is 1.10.7,  
```
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 41, in load_command_class
    return module.Command()
  File "/usr/local/lib/python3.5/site-packages/collectfast/management/commands/collectstatic.py", line 35, in __init__
    if self.storage.preload_metadata is not True:
  File "/usr/local/lib/python3.5/site-packages/django/utils/functional.py", line 235, in inner
    return func(self._wrapped, *args)
AttributeError: 'StaticFilesStorage' object has no attribute 'preload_metadata'
```

**Comment by luojiyin1987** [comment]
from    #30
[fix pr](https://github.com/antonagestam/collectfast/pull/124)

## solve
 write 
`Collectfast==0.5.2`
to    requirements.txt    to  solve  it. 
I hope it can  help others.
