### ISSUE TITLE
0.6.2 CI now fails

### ISSUE THREAD

**Issue by jayvdb** [antonagestam/collectfast#132]
Re-running CI on 0.6.2 results in errors

https://travis-ci.org/jayvdb/collectfast/builds/495173846

```py
======================================================================
ERROR: collectfast.tests.test_command (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: collectfast.tests.test_command
Traceback (most recent call last):
  File "/opt/python/3.6.3/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/python/3.6.3/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/travis/build/jayvdb/collectfast/collectfast/tests/test_command.py", line 7, in <module>
    from .utils import test, clean_static_dir, create_static_file, override_setting
  File "/home/travis/build/jayvdb/collectfast/collectfast/tests/utils.py", line 10, in <module>
    import boto
  File "/home/travis/build/jayvdb/collectfast/.tox/py36-django200/lib/python3.6/site-packages/boto/__init__.py", line 1216, in <module>
    boto.plugin.load_plugins(config)
  File "/home/travis/build/jayvdb/collectfast/.tox/py36-django200/lib/python3.6/site-packages/boto/plugin.py", line 93, in load_plugins
    _import_module(file)
  File "/home/travis/build/jayvdb/collectfast/.tox/py36-django200/lib/python3.6/site-packages/boto/plugin.py", line 75, in _import_module
    return imp.load_module(name, file, filename, data)
  File "/home/travis/build/jayvdb/collectfast/.tox/py36-django200/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/travis/build/jayvdb/collectfast/.tox/py36-django200/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "/usr/lib/python2.7/dist-packages/google_compute_engine/boto/compute_auth.py", line 19, in <module>
    from google_compute_engine import logger
ModuleNotFoundError: No module named 'google_compute_engine'
======================================================================
ERROR: collectfast.tests.test_etag (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: collectfast.tests.test_etag
Traceback (most recent call last):
  File "/opt/python/3.6.3/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/python/3.6.3/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/travis/build/jayvdb/collectfast/collectfast/tests/test_etag.py", line 7, in <module>
    from storages.backends.s3boto import S3BotoStorage
  File "/home/travis/build/jayvdb/collectfast/.tox/py36-django200/lib/python3.6/site-packages/storages/backends/s3boto.py", line 25, in <module>
    from boto import __version__ as boto_version
  File "/home/travis/build/jayvdb/collectfast/.tox/py36-django200/lib/python3.6/site-packages/boto/__init__.py", line 1216, in <module>
    boto.plugin.load_plugins(config)
AttributeError: module 'boto' has no attribute 'plugin'
```

When I try to run it on openSUSE build environment, with latest moto, I get different errors:

```py
======================================================================
ERROR: test_basics (collectfast.tests.utils.test_basics)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/moto/core/models.py", line 74, in wrapper
    result = func(*args, **kwargs)
  File "collectfast/tests/utils.py", line 33, in wraps
    boto.connect_s3().create_bucket(django_settings.AWS_STORAGE_BUCKET_NAME)
  File "/usr/lib/python2.7/site-packages/boto/__init__.py", line 141, in connect_s3
    return S3Connection(aws_access_key_id, aws_secret_access_key, **kwargs)
  File "/usr/lib/python2.7/site-packages/boto/s3/connection.py", line 194, in __init__
    validate_certs=validate_certs, profile_name=profile_name)
  File "/usr/lib/python2.7/site-packages/boto/connection.py", line 569, in __init__
    host, config, self.provider, self._required_auth_capability())
  File "/usr/lib/python2.7/site-packages/boto/auth.py", line 1021, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV1Handler'] Check your credentials
```

**Comment by antonagestam** [comment]
Yes, I believe this is the same reason master fails, looked into to it some time ago but haven't had the time to fix it. This is due to changes in the dependencies and "not a real bug", nevertheless needs to be fixed at some point.

**Comment by jayvdb** [comment]
The tests get a bit further with https://github.com/jayvdb/collectfast/commit/c58d98da585d4cf702f284a1449c7daccb938d56 , but many are still failing.

**Comment by jayvdb** [comment]
fwiw, you can see the openSUSE 0.6.2 logs at https://build.opensuse.org/package/show/home:jayvdb:django/python-Collectfast

**Comment by antonagestam** [comment]
This is the moto issue: https://github.com/spulec/moto/issues/1793

Spent another 2 hours trying to fix this ...

**Comment by antonagestam** [comment]
I'm considering going back to using a real S3 bucket for integration tests instead of moto ...
