### ISSUE TITLE
installation error: django==1.8.2 , python3.4

### ISSUE THREAD

**Issue by abal09** [antonagestam/collectfast#65]
Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/abal/isocutter/build/collectfast/setup.py", line 10, in <module>
        long_description=open('README.rst').read(),
      File "/home/abal/isocutter/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 12: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/abal/isocutter/build/collectfast/setup.py", line 10, in <module>

    long_description=open('README.rst').read(),

  File "/home/abal/isocutter/lib/python3.4/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 12: ordinal not in range(128)

**Comment by abal09** [comment]
I had to set 
export LC_ALL=en_US.UTF-8
to solve

**Comment by antonagestam** [comment]
@abal09 What version of Django and Python are you using?

**Comment by abal09** [comment]
I was using django==1.8.2 , python3.4
