### ISSUE TITLE
Update to work with boto v3

### ISSUE THREAD

**Issue by pydolan** [antonagestam/collectfast#77]
Boto v3 support was recently added to django-storages (https://github.com/jschneier/django-storages/issues/57), but when using collectfast with boto v3, an error is generated when calling collectstatic: `AttributeError: 's3.Bucket' object has no attribute 'lookup'`

**Comment by m-vdb** [comment]
full backtrace
```python
Traceback (most recent call last):
  File "./manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "::snip::/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "::snip::/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "::snip::/env/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "::snip::/env/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "::snip::/env/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 176, in handle
    collected = self.collect()
  File "::snip::/env/lib/python2.7/site-packages/collectfast/management/commands/collectstatic.py", line 68, in collect
    ret = super(Command, self).collect()
  File "::snip::/env/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 107, in collect
    handler(path, prefixed_path, storage)
  File "::snip::/env/lib/python2.7/site-packages/collectfast/management/commands/collectstatic.py", line 120, in copy_file
    storage_lookup = self.get_lookup(normalized_path)
  File "::snip::/env/lib/python2.7/site-packages/collectfast/management/commands/collectstatic.py", line 94, in get_lookup
    self.lookups[path] = self.get_storage_lookup(path)
  File "::snip::/env/lib/python2.7/site-packages/collectfast/management/commands/collectstatic.py", line 81, in get_storage_lookup
    return self.storage.bucket.lookup(path)
AttributeError: 's3.Bucket' object has no attribute 'lookup'
```

**Comment by antonagestam** [comment]
@pydolan @m-vdb I'd be happy to review and merge pull requests for this! 👍

**Comment by jdotjdot** [comment]
What is it doing there, looking up the file?  In this case [this documentation](http://boto3.readthedocs.io/en/latest/guide/migrations3.html#storing-data) is what's relevant--but note that the boto2 `Bucket.lookup()` method that is failing was [deprecated](http://boto.cloudhackers.com/en/latest/ref/s3.html#boto.s3.bucket.Bucket.lookup) anyway

**Comment by antonagestam** [comment]
@jdotjdot Thanks for the pr. 🍰  I actually started working on this yesterday as well and rewrote the cache mechanics so that only the etag is stored and not the entire lookup.  Working on adjusting the tests atm. :)
